
import { Task, Region, Category, Priority, Status } from './types';

export const INITIAL_TASKS: Task[] = [
  {
    id: '1',
    region: Region.BRAZIL,
    title: 'Backup Car',
    description: 'Gestão de veículos reserva para a frota regional.',
    action: 'Monitorar disponibilidade e custos.',
    category: Category.PROJETOS,
    priority: Priority.MEDIA,
    owner: 'Monica Silva',
    support: 'Adriana Cosso',
    startDate: '2023-10-12',
    status: Status.EM_ANDAMENTO,
    progress: 80,
    dueDate: '2025-02-15',
    escalation: '',
    notes: 'Ajustar contratos até o fim do mês.',
    timeline: '12/10: Início do projeto. 20/11: Primeira revisão de custos finalizada.'
  },
  {
    id: '2',
    region: Region.BRAZIL,
    title: 'Inteligência Artificial (Atendimento)',
    description: 'Implementação de chatbots de IA no atendimento ao cliente.',
    action: 'Validar fluxos de conversação.',
    category: Category.QUALIDADE,
    priority: Priority.ALTA,
    owner: 'Nilson Marcos',
    support: 'Rebeca Laiz',
    startDate: '2023-01-05',
    status: Status.EM_ANDAMENTO,
    progress: 50,
    dueDate: '2025-06-30',
    escalation: 'Atrasado',
    notes: 'Necessário feedback da engenharia.',
    timeline: '05/01: Escopo definido. 15/03: Protótipo em testes.'
  },
  {
    id: '3',
    region: Region.ARGENTINA,
    title: 'Carros falhando - Lote Argo',
    description: 'Investigação de falhas mecânicas no lote recente.',
    action: 'Revisar o lote e emitir laudo.',
    category: Category.PRODUTO,
    priority: Priority.ALTA,
    owner: 'Lucas João',
    support: 'João Pedro',
    startDate: '2024-02-10',
    status: Status.EM_ANDAMENTO,
    progress: 10,
    dueDate: '2025-02-27',
    escalation: '',
    notes: 'Urgent: Falha detectada em 5% da amostra.',
    timeline: '10/02: Abertura do chamado técnico.'
  },
  {
    id: '4',
    region: Region.CHILE,
    title: 'Processo PAF (Recuperação)',
    description: 'Recuperação de impostos e créditos fiscais no Chile.',
    action: 'Audit fiscal completo.',
    category: Category.FINANCEIRO,
    priority: Priority.MEDIA,
    owner: 'Tatiana Diniz',
    support: 'Flavia Maria',
    startDate: '2023-05-15',
    status: Status.CONCLUIDO,
    progress: 100,
    dueDate: '2024-12-31',
    escalation: '',
    notes: 'Concluído com economia de 15%.',
    timeline: '15/05/23: Início da auditoria. 20/12/24: Finalização e entrega do relatório.'
  },
  {
    id: '5',
    region: Region.SOUTH_AMERICA,
    title: 'Governança Customer Care',
    description: 'Unificação dos processos de atendimento na LatAm.',
    action: 'Workshops regionais.',
    category: Category.PROJETOS,
    priority: Priority.BAIXA,
    owner: 'Adriana Cosso',
    support: 'Monica Silva',
    startDate: '2024-01-01',
    status: Status.NAO_INICIADO,
    progress: 0,
    dueDate: '2025-12-31',
    escalation: '',
    notes: 'Aguardando aprovação orçamentária.',
    timeline: '01/01: Planejamento inicial.'
  }
];
